responseTimeout: 5000
torchrun:
    nproc-per-node: 1 
handler:
    model_path: "/scratch/weights/hub/models--meta-llama--Llama-2-70b-chat-hf/snapshots/482493c310224b78427158ed51b932a83aba5826" #the path to the checkpoints, in this example downloaded file. Please change to your model path.
    quantize: "nf4"
    num_gpu_per_model: 1
    gpu_max_memory: 4.8e10
